inputs:
  persist-credentials:
    type: boolean
    required: false
    default: true
  build-command:
    type: string
    required: true
    default: build
  test-command:
    type: string
    required: true
    default: test
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: ${{ inputs.persist-credentials  }}

    - uses: joekarow/act-which-package-mgr@v1.0.0
      id: pm

    - uses: bubkoo/rsw-a/.github/actions/setup-pnpm@master
      if: ${{ steps.pm.outputs.package_manager == 'pnpm' }}
      with:
        build-command: ${{ inputs.build-command }}
        test-command: ${{ inputs.test-command }}

    - uses: bubkoo/rsw-a/.github/actions/setup-yarn@master
      if: ${{ steps.pm.outputs.package_manager == 'yarn' }}
      with:
        build-command: ${{ inputs.build-command }}
        test-command: ${{ inputs.test-command }}

    - uses: bubkoo/rsw-a/.github/actions/setup-npm@master
      if: ${{ steps.pm.outputs.package_manager == 'npm' }}
      with:
        build-command: ${{ inputs.build-command }}
        test-command: ${{ inputs.test-command }}
