inputs:
  persist-credentials:
    type: boolean
    default: true
  build-command:
    type: string
  test-command:
    type: string
  manual-command:
    type: string
runs:
  using: composite
  steps:
    # checkout
    - uses: actions/checkout@v3
      with:
        persist-credentials: ${{ inputs.persist-credentials }}

    # detect package manager
    - uses: wow-actions/get-package-manager@v1
      id: getpm
    - run: echo "PACKAGE_MANAGER=${{ steps.getpm.outputs.pm }}" >> $GITHUB_ENV
      shell: bash

    # setup cache and install deps
    - uses: bubkoo/reusable-workflows/.github/actions/setup-pnpm@master
      if: ${{ env.PACKAGE_MANAGER == 'pnpm' }}
    - uses: bubkoo/reusable-workflows/.github/actions/setup-yarn@master
      if: ${{ env.PACKAGE_MANAGER == 'yarn' }}
    - uses: bubkoo/reusable-workflows/.github/actions/setup-npm@master
      if: ${{ env.PACKAGE_MANAGER == 'npm' }}

    # run test command specified in package.json
    - run: ${{ env.PACKAGE_MANAGER }} run ${{ inputs.test-command }}
      if: ${{ inputs.test-command != '' && inputs.test-command != 'false' }}
      shell: bash

    # run build command specified in package.json
    - run: ${{ env.PACKAGE_MANAGER }} run ${{ inputs.build-command }}
      if: ${{ inputs.build-command != '' && inputs.build-command != 'false' }}
      shell: bash

    # execute manual command
    - run: ${{ env.PACKAGE_MANAGER }} ${{ inputs.manual-command }}
      if: ${{ inputs.manual-command != ''}}
      shell: bash
