inputs:
  build-command:
    type: string
    required: true
  test-command:
    type: string
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Get npm cache directory
      id: npm-cache-dir
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      shell: bash

    - uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm install --no-frozen-lockfile --ignore-scripts
      shell: bash

    - run: npm run ${{ inputs.build-command }}
      if: ${{ inputs.build-command != '' && inputs.build-command != 'false' }}
      shell: bash

    - run: yarn run ${{ inputs.test-command }}
      if: ${{ inputs.test-command != '' && inputs.test-command != 'false' }}
      shell: bash
