name: 🔑　Generate Token
description: Generate an app token used in the next steps.
runs:
  using: composite
  steps:
    - name: 🔑　Generate Token
      uses: wow-actions/use-app-token@v2
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}
