inputs:
  github-token:
    type: string
  app-id:
    type: string
  private-key:
    type: string
runs:
  using: composite
  steps:
    - uses: wow-actions/use-app-token@v2
      if: ${{ inputs.app-id != '' && inputs.private-key != '' }}
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.private-key }}

    - name: Release with App Token
      if: ${{ env.BOT_TOKEN != '' }}
      uses: wow-actions/release-github-action@v2
      env:
        GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
        GIT_AUTHOR_NAME: ${{ env.BOT_NAME }}[bot]
        GIT_AUTHOR_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: ${{ env.BOT_NAME }}[bot]
        GIT_COMMITTER_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com

    - name: Release with GitHub Token
      if: ${{ input.github-token != '' }}
      uses: wow-actions/release-github-action@v2
      env:
        GITHUB_TOKEN: ${{ input.github-token }}
