inputs:
  npm-token:
    type: string
  github-token:
    type: string
  app-id:
    type: string
  private-key:
    type: string
  build-command:
    type: string
  test-command:
    type: string
  manual-command:
    type: string
runs:
  using: composite
  steps:
    # prepare repo
    - uses: bubkoo/reusable-workflows/.github/actions/prepare-repo@master
      with:
        persist-credentials: false
        test-command: ${{ inputs.test-command }}
        build-command: ${{ inputs.build-command }}
        manual-command: ${{ inputs.manual-command }}

    # install srm cli and required deps
    - run: yarn global add @semantic-release-monorepo/cli semantic-release @semantic-release/changelog @semantic-release/git -s
      if: ${{ env.PACKAGE_MANAGER == 'yarn' }}
      shell: bash
    - run: ${{ env.PACKAGE_MANAGER }} install @semantic-release-monorepo/cli semantic-release @semantic-release/changelog @semantic-release/git -g -s
      if: ${{ env.PACKAGE_MANAGER == 'npm' || env.PACKAGE_MANAGER == 'pnpm' }}
      shell: bash

    - name: Generate app token
      uses: wow-actions/use-app-token@v2
      if: ${{ inputs.app-id != '' && inputs.private-key != '' }}
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.private-key }}

    - name: Release with App Token
      if: ${{ env.BOT_TOKEN != '' }}
      run: srm --combine-commits
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
        NPM_TOKEN: ${{ inputs.npm-token }}
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
        GIT_AUTHOR_NAME: ${{ env.BOT_NAME }}[bot]
        GIT_AUTHOR_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: ${{ env.BOT_NAME }}[bot]
        GIT_COMMITTER_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com

    - name: Release with GitHub Token
      if: ${{ inputs.github-token != '' }}
      run: srm --combine-commits
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
