inputs:
  npm-token:
    type: string
  github-token:
    type: string
  app-id:
    type: string
  private-key:
    type: string

runs:
  using: composite
  steps:
    - name: "checking environment variables"
      shell: bash
      run: |
        echo "${{inputs.npm-token}}"
        echo "${{inputs.github-token}}"
        echo "${{inputs.app-id-token}}"
        echo "${{inputs.private-key}}"
    - uses: wow-actions/use-app-token@v2
      if: ${{ inputs.app-id != '' && inputs.private-key != '' }}
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.private-key }}

    - uses: hmarr/debug-action@v2

    - name: Release with App Token
      if: ${{ env.BOT_TOKEN != '' }}
      uses: cycjimmy/semantic-release-action@v3
      with:
        extends: '@bubkoo/semantic-release-config'
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
        GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
        GIT_AUTHOR_NAME: ${{ env.BOT_NAME }}[bot]
        GIT_AUTHOR_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: ${{ env.BOT_NAME }}[bot]
        GIT_COMMITTER_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com

    - name: Release with GitHub Token
      if: ${{ inputs.github-token != '' }}
      uses: cycjimmy/semantic-release-action@v3
      with:
        extends: '@bubkoo/semantic-release-config'
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
      env:
        NPM_TOKEN: ${{ inputs.npm-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
