runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: false

    - run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      id: pnpm-cache
      shell: bash

    - name: cache pnpm
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - run: pnpm install --no-frozen-lockfile --ignore-scripts
      shell: bash
