name: Release
on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
        description: Repository name with owner. For example, actions/checkout
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️　Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          persist-credentials: false
      - name: 🚧　Install
        run: yarn install
      - name: 📦　Build
        run: yarn build
      - uses: ./.github/actions/generate-token
      - name: 📦　Release
        uses: wow-actions/release-github-action@v2
        env:
          GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
          GIT_AUTHOR_NAME: ${{ env.BOT_NAME }}[bot]
          GIT_AUTHOR_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ env.BOT_NAME }}[bot]
          GIT_COMMITTER_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com
