name: 🚀　Release

on:
  workflow_call:
    inputs:
      app-id:
        type: string
        required: false
      private-key:
        type: string
        required: false
      build-command:
        type: string
        required: false
        default: build
      test-command:
        type: string
        required: false
        default: test
      gpr:
        type: string
        required: false
        default: false
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/rsw-a/.github/actions/prepare-repo@master
        with:
          persist-credentials: false
          build-command: ${{ inputs.build-command }}
          test-command: ${{ inputs.test-command }}

      - uses: wow-actions/use-app-token@v2
        if: ${{ inputs.app-id != '' && inputs.private-key != '' }}
        with:
          app_id: ${{ inputs.app-id }}
          private_key: ${{ inputs.private-key }}

      - uses: hmarr/debug-action@v2

      # - name: 📦　Semantic Release
      #   uses: cycjimmy/semantic-release-action@v3
      #   id: semantic
      #   with:
      #     extends: '@bubkoo/semantic-release-config'
      #     extra_plugins: |
      #       @semantic-release/changelog
      #       @semantic-release/git
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
      #     GIT_AUTHOR_NAME: ${{ env.BOT_NAME }}[bot]
      #     GIT_AUTHOR_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com
      #     GIT_COMMITTER_NAME: ${{ env.BOT_NAME }}[bot]
      #     GIT_COMMITTER_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com

      # - name: 🎉　Setup Node.js with GitHub Package Registry
      #   if: steps.semantic.outputs.new_release_published == 'true'
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      #     registry-url: https://npm.pkg.github.com
      #     scope: bubkoo

      # - name: 🔀　Publish To GitHub Package Registry
      #   if: steps.semantic.outputs.new_release_published == 'true'
      #   run: |
      #     sed -i 's/\("name"\:[[:space:]]*"\)\(html-to-image"\)/\1@bubkoo\/\2/' package.json
      #     npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
