on:
  workflow_call:
    secrets:
      github-token:
        required: false
      app-id:
        type: string
        required: false
      private-key:
        type: string
        required: false
    inputs:
      build-command:
        type: string
        required: false
        default: build
      test-command:
        type: string
        required: false
        default: test
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/reusable-workflows/.github/actions/prepare-repo@master
        with:
          persist-credentials: false
          build-command: ${{ inputs.build-command }}
          test-command: ${{ inputs.test-command }}

      - uses: wow-actions/use-app-token@v2
        if: ${{ inputs.app-id != '' && inputs.private-key != '' }}
        with:
          app_id: ${{ inputs.app-id }}
          private_key: ${{ inputs.private-key }}

      - name: Release with App Token
        if: ${{ env.BOT_TOKEN != '' }}
        uses: wow-actions/release-github-action@v2
        env:
          GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
          GIT_AUTHOR_NAME: ${{ env.BOT_NAME }}[bot]
          GIT_AUTHOR_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ env.BOT_NAME }}[bot]
          GIT_COMMITTER_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com

      - name: Release with GitHub Token
        if: ${{ input.github-token != '' }}
        uses: wow-actions/release-github-action@v2
        env:
          GITHUB_TOKEN: ${{ input.github-token }}
