on:
  workflow_call:
    secrets:
      npm-token:
        required: true
      github-token:
        required: false
      app-id:
        required: false
      private-key:
        required: false    

    inputs:
      build-command:
        type: string
        default: build
      test-command:
        type: string
        default: test
      extends:
        type: string
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/reusable-workflows/.github/actions/prepare-repo@master
        with:
          persist-credentials: false
          build-command: ${{ inputs.build-command }}
          test-command: ${{ inputs.test-command }}

      - uses: wow-actions/use-app-token@v2
        with:
          app_id: ${{ secrets.app-id }}
          private_key: ${{ secrets.private-key }}

      - uses: hmarr/debug-action@v2

      - name: Release with App Token
        if: ${{ env.BOT_TOKEN != '' }}
        uses: cycjimmy/semantic-release-action@v3
        with:
          extends: '@bubkoo/semantic-release-config'
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          NPM_TOKEN: ${{ secrets.npm-token }}
          GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
          GIT_AUTHOR_NAME: ${{ env.BOT_NAME }}[bot]
          GIT_AUTHOR_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ env.BOT_NAME }}[bot]
          GIT_COMMITTER_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com

      - name: Release with GitHub Token
        if: ${{ secrets.github-token != '' }}
        uses: cycjimmy/semantic-release-action@v3
        with:
          extends: '@bubkoo/semantic-release-config'
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          NPM_TOKEN: ${{ secrets.npm-token }}
          GITHUB_TOKEN: ${{ secrets.github-token }}
