inputs:
  build-command:
    type: string
    required: true
    default: build
  test-command:
    type: string
    required: true
    default: test
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v3
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - run: yarn install
      shell: bash

    - run: yarn run ${{ inputs.build-command }}
      if: ${{ inputs.build-command != '' && inputs.build-command != 'false' }}
      shell: bash

    - run: yarn run ${{ inputs.test-command }}
      if: ${{ inputs.test-command != '' && inputs.test-command != 'false' }}
      shell: bash
